### PR TITLE
feat. - more uniforms

### PR DESCRIPTION
**Pull request by jbritain**
This adds the following uniforms

- `far`
- `heldBlockLightValue`
- `heldBlockLightValue2`
- `playerMood`
- `wetness`

and also fixes some typos.

### CODE REVIEW

**Comment by jbritain** [comment]
I think the links between `wetness` and `rainStrength` might have broken something so check that, idk how astro does links

**Comment by WhyFenceCode** [comment]
Hi @jbritain this repo has moved: https://github.com/IrisShaders/DocsPage

**Comment by WhyFenceCode** [comment]
also please mark them in this exel sheet before beinging work next time: https://docs.google.com/spreadsheets/d/1gFDjV_GzEMIDAxtluWZkBXsEPauj5ftB7rn9wX5X9Kc/

**Comment by jbritain** [comment]
Will do. You probably ought to delete this repo if it's not the main one.

**Pull request closed without merging**
